=== AshishKrSingh001/CodeRepo/XML/ExternalDTD.dtd
<!ELEMENT student (name,age,id,roll_no,mob_no,add)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT roll_no (#PCDATA)>
<!ELEMENT mob_no (#PCDATA)>
<!ELEMENT add (#PCDATA)>

=== AshishKrSingh001/CodeRepo/XML/ExternalDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student SYSTEM "ExternalDTD.dtd">
<student>
	<name>Ashish</name>
	<age>21</age>
	<id>123</id>
	<roll_no>85</roll_no>
	<mob_no>7896541230</mob_no>
	<add>Thakurganj</add>
	<name>Ashish</name>
	<age>21</age>
	<id>123</id>
	<roll_no>85</roll_no>
	<mob_no>7896541230</mob_no>
	<add>Thakurganj</add>
</student>
