=== AshishKrSingh001/CodeRepo/XML/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<a:schema xmlns:a="schema_namespace">
	<a:element name="employee">
		<a:complexType>
			<a:sequence>
				<a:element name="name" type="a:string"/>
				<a:element name="id" type="a:string"/>
				<a:element name="add">
					<a:complexType>
						<a:sequence>
							<a:element name="city" type="a:string"/>
							<a:element name="pincode" type="a:string"/>
						</a:sequence>
					</a:complexType>
				</a:element>
			</a:sequence>
		</a:complexType>
	</a:element>
</a:schema>

=== AshishKrSingh001/CodeRepo/XML/schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<employee xmlns:X="xxx" X:schemaLocation="schema.xsd">
	<name>Ashish</name>
	<id>13089</id>
	<add>
		<city>patna</city>
		<pincode>11111</pincode>
	</add>
	<name>Ashish</name>
	<id>13089</id>
	<add>
		<city>patna</city>
		<pincode>11111</pincode>
	</add>
	<name>Ashish</name>
	<id>13089</id>
	<add>
		<city>patna</city>
		<pincode>11111</pincode>
	</add>
</employee>
